FROM python:3.11-slim
WORKDIR /app
COPY ./backend/requirements.txt ./requirements.txt
RUN pip install --user --no-cache-dir -r requirements.txt
COPY ./backend/ ./
ENV PATH=/root/.local/bin:$PATH
EXPOSE 5000
CMD ["python", "./app.py"]
